
export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just for You",
        description: "Get interview questions and model answer based on your role, experience and specific focus areas - ",
    },
    {
        id: "02",
        title: "Learn at Your Own Pace",
        description: "Expand answers only when you are ready, Dive deeper into any concept instantly with AI-Powered detailed Answers",

    },
    {
        id: "03",
        title: "Capture Your Insights",
        description: "Add personal notes to any question and pin important ones to the top - making your learning more organization more effectively",
    },
    {
        id: "04",
        title: 'Understand the "Why" Behind Answers',
        description: "Beyond just answers - unlock detailed concept explainations generated by AI, helping you truly masters your skills ",
    },
    {
        id: "05",
        title: "Save, Organize, and Revisit",
        description: "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right now! ",
    }
]